### ISSUE TITLE
Replicating Joos et al., 2013 IRF function

### ISSUE THREAD

**Issue by badgley** [carbonplan/ton-year#2]
Section 4.1 of Joos et al. 2013  reports the following fractions of a CO2 emission pulse remaining: 

| Year | Joos2013 Fraction Remaining| Calculated Fraction Remaining |  
| -- | -- | -- | 
| 20 | 0.6 ± 0.14 |  0.59 |
| 100 | 0.41 ± 0.13 |  -- |
| 1000 | 0.25 ± 0.09 |  0.235 | 

So we're pretty close but drifting at the 1,000 year timeframe. 

IPCC AR5 Chapter 8 Supplementary Material, Table 8.SM.11 also reports time-integrated IRF mean values using the parameters from Joos et al. 2013: 

| Year | IPCC reported Cumulative IRF | Calculated Cumulative IRF | 
| -- | -- | -- | 
|20 | 14.2 | 14.2 |
| 100 | 52.4 | 52.4 |  

So in this case we're spot on! 

What's causing the divergence when comparing to Joos et al., 2013 but agreement when comparing to AR5 Chapter 8?

**Comment by badgley** [comment]
@freyac we determined this wasn't a bug, right? instead it had something to do with using parameters fit across all the models vs some of the models? i also think that issue #6 might resolve/partially address this issue? happy to close if we think using `ghgforcing` code will address!

**Comment by jhamman** [comment]
In #7, I added to the tonyear test suite. It could be nice to drop these benchmarks into the test suite.

**Comment by freyac** [comment]
@badgley  - yup! We determined that the numbers reported in Section 4.1 of Joos et al. (2013) were multi-model mean results rather than the result of the sum of exponentials (the IRF we're implementing) that was fitted to that model ensemble. 

Table 8.SM.11 reports time-integrated IRF mean values are calculated from the with the sum of exponentials, which is why we match them exactly. Joos et al. (2013) also reports the time-integrated IRF values Table 4, which again, we match exactly. 

@jhamman - will add these checks to the test suite!

**Comment by freyac** [comment]
Oh, and as for the the ghgforcing code,

**Comment by freyac** [comment]
(Accidentally closed this! Will plan to close when the time-integrated IRF values are added to the test suite.)
